//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarringsDbProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSCREDENTIAL
    {
        public long USERSID { get; set; }
        public string USERNAME { get; set; }
        public string USERNAMEPASSWORD { get; set; }
        public string USERTOKEN { get; set; }
    }
}
