//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarringsDbProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCredentials
    {
        public long UserID { get; set; }
        public string Username { get; set; }
        public byte[] UsernamePassword { get; set; }
        public string UserEmail { get; set; }
        public string UserToken { get; set; }
        public System.DateTime UserRegistrationDate { get; set; }
    }
}
